# AUTO-GENERATED. DO NOT EDIT DIRECTLY.
"""Generated static model registry."""

from collections.abc import Mapping
from types import MappingProxyType
from typing import Final

from cdxml_om.core.models import CDXMLElement

from .models import (
    AltGroup,
    Annotation,
    Arrow,
    BioShape,
    Bond,
    Border,
    BracketAttachment,
    BracketedGroup,
    CDXMLRoot,
    ChemicalProperty,
    Color,
    ColoredMolecularArea,
    ColorTable,
    Constraint,
    CrossingBond,
    CrossReference,
    Curve,
    EmbeddedObject,
    Font,
    FontTable,
    Fragment,
    Geometry,
    GEPBand,
    GEPLane,
    GEPPlate,
    Graphic,
    Group,
    Marker,
    Node,
    ObjectTag,
    Page,
    PlasmidMap,
    PlasmidMarker,
    PlasmidRegion,
    ReactionScheme,
    ReactionStep,
    RegistryNumber,
    Represent,
    RLogic,
    RLogicItem,
    Sequence,
    SGComponent,
    SGDatum,
    Spectrum,
    Splitter,
    StoichiometryGrid,
    Table,
    TemplateGrid,
    Text,
    TextRun,
    TLCLane,
    TLCPlate,
    TLCSpot,
)
from .schema_metadata import SCHEMA_HASH as SCHEMA_HASH

MODEL_REGISTRY: Final[Mapping[str, type[CDXMLElement]]] = MappingProxyType(
    {
        "alt_group": AltGroup,
        "annotation": Annotation,
        "arrow": Arrow,
        "bio_shape": BioShape,
        "bond": Bond,
        "border": Border,
        "bracket_attachment": BracketAttachment,
        "bracketed_group": BracketedGroup,
        "cdxml_root": CDXMLRoot,
        "chemical_property": ChemicalProperty,
        "color": Color,
        "color_table": ColorTable,
        "colored_molecular_area": ColoredMolecularArea,
        "constraint": Constraint,
        "cross_reference": CrossReference,
        "crossing_bond": CrossingBond,
        "curve": Curve,
        "embedded_object": EmbeddedObject,
        "font": Font,
        "font_table": FontTable,
        "fragment": Fragment,
        "geometry": Geometry,
        "gep_band": GEPBand,
        "gep_lane": GEPLane,
        "gep_plate": GEPPlate,
        "graphic": Graphic,
        "group": Group,
        "marker": Marker,
        "node": Node,
        "object_tag": ObjectTag,
        "page": Page,
        "plasmid_map": PlasmidMap,
        "plasmid_marker": PlasmidMarker,
        "plasmid_region": PlasmidRegion,
        "reaction_scheme": ReactionScheme,
        "reaction_step": ReactionStep,
        "registry_number": RegistryNumber,
        "represent": Represent,
        "rlogic": RLogic,
        "rlogic_item": RLogicItem,
        "sequence": Sequence,
        "sg_component": SGComponent,
        "sg_datum": SGDatum,
        "spectrum": Spectrum,
        "splitter": Splitter,
        "stoichiometry_grid": StoichiometryGrid,
        "table": Table,
        "template_grid": TemplateGrid,
        "text": Text,
        "text_run": TextRun,
        "tlc_lane": TLCLane,
        "tlc_plate": TLCPlate,
        "tlc_spot": TLCSpot,
    }
)
OBJECT_BY_XML_TAG: Final[Mapping[str, type[CDXMLElement]]] = MappingProxyType(
    {
        "CDXML": CDXMLRoot,
        "altgroup": AltGroup,
        "annotation": Annotation,
        "arrow": Arrow,
        "b": Bond,
        "bioshape": BioShape,
        "border": Border,
        "bracketattachment": BracketAttachment,
        "bracketedgroup": BracketedGroup,
        "chemicalproperty": ChemicalProperty,
        "color": Color,
        "coloredmoleculararea": ColoredMolecularArea,
        "colortable": ColorTable,
        "constraint": Constraint,
        "crossingbond": CrossingBond,
        "crossreference": CrossReference,
        "curve": Curve,
        "embeddedobject": EmbeddedObject,
        "font": Font,
        "fonttable": FontTable,
        "fragment": Fragment,
        "geometry": Geometry,
        "gepband": GEPBand,
        "geplane": GEPLane,
        "gepplate": GEPPlate,
        "graphic": Graphic,
        "group": Group,
        "marker": Marker,
        "n": Node,
        "objecttag": ObjectTag,
        "page": Page,
        "plasmidmap": PlasmidMap,
        "plasmidmarker": PlasmidMarker,
        "plasmidregion": PlasmidRegion,
        "regnum": RegistryNumber,
        "represent": Represent,
        "rlogic": RLogic,
        "rlogicitem": RLogicItem,
        "s": TextRun,
        "scheme": ReactionScheme,
        "sequence": Sequence,
        "sgcomponent": SGComponent,
        "sgdatum": SGDatum,
        "spectrum": Spectrum,
        "splitter": Splitter,
        "step": ReactionStep,
        "stoichiometrygrid": StoichiometryGrid,
        "t": Text,
        "table": Table,
        "templategrid": TemplateGrid,
        "tlclane": TLCLane,
        "tlcplate": TLCPlate,
        "tlcspot": TLCSpot,
    }
)
OBJECT_BY_SPEC_ID: Final[Mapping[str, type[CDXMLElement]]] = MODEL_REGISTRY
