# AUTO-GENERATED. DO NOT EDIT DIRECTLY.
"""Properties grouped by logical schema owner: constraint."""

from __future__ import annotations

from collections.abc import Mapping
from types import MappingProxyType
from typing import Final

from ..provenance.revvity_dtd import (
    P_0225b4e8c4563a5b4914,
    P_2d1e7d57384e1f342f7d,
    P_7e187206c5054c7a31c8,
    P_68fecebb0c4ad436cb89,
    P_d4919fe040ff8f0c55d9,
    P_e8a94b55eaeb5c567ab5,
)
from ..provenance.sdk_page_constraint import (
    P_04211eae1ae6a4966e8e,
    P_15b5b13e1f24595e8e6b,
    P_395d6835593785ebb5f0,
    P_4561a1e5bae152c58cf8,
    P_c5cbe6abb9f86363eb4d,
)
from ..types import PropertyMetadata

PROPERTY_METADATA_GROUP: Final[Mapping[str, PropertyMetadata]] = MappingProxyType(
    {
        "dtd.constraint.constraint_max": PropertyMetadata(
            owners=("constraint",),
            name="constraint_max",
            xml_name="ConstraintMax",
            storage="attribute",
            cdx_id=2949,
            cdx_constant="kCDXProp_ConstraintMax",
            datatype="float",
            codec="float",
            required=False,
            default=None,
            cardinality="one",
            reference_target=None,
            reference_many=False,
            enum=None,
            status="known",
            provenance=(
                P_e8a94b55eaeb5c567ab5,
                P_04211eae1ae6a4966e8e,
            ),
            xml_aliases=(),
        ),
        "dtd.constraint.constraint_min": PropertyMetadata(
            owners=("constraint",),
            name="constraint_min",
            xml_name="ConstraintMin",
            storage="attribute",
            cdx_id=2948,
            cdx_constant="kCDXProp_ConstraintMin",
            datatype="float",
            codec="float",
            required=False,
            default=None,
            cardinality="one",
            reference_target=None,
            reference_many=False,
            enum=None,
            status="known",
            provenance=(
                P_2d1e7d57384e1f342f7d,
                P_c5cbe6abb9f86363eb4d,
            ),
            xml_aliases=(),
        ),
        "dtd.constraint.constraint_type": PropertyMetadata(
            owners=("constraint",),
            name="constraint_type",
            xml_name="ConstraintType",
            storage="attribute",
            cdx_id=2947,
            cdx_constant="kCDXProp_ConstraintType",
            datatype="string",
            codec="string",
            required=False,
            default="Unknown",
            cardinality="one",
            reference_target=None,
            reference_many=False,
            enum="dtd.constraint_type.eba13b7c",
            status="known",
            provenance=(
                P_0225b4e8c4563a5b4914,
                P_4561a1e5bae152c58cf8,
            ),
            xml_aliases=(),
        ),
        "dtd.constraint.dihedral_is_chiral": PropertyMetadata(
            owners=("constraint",),
            name="dihedral_is_chiral",
            xml_name="DihedralIsChiral",
            storage="attribute",
            cdx_id=2951,
            cdx_constant="kCDXProp_DihedralIsChiral",
            datatype="boolean",
            codec="bool",
            required=False,
            default=False,
            cardinality="one",
            reference_target=None,
            reference_many=False,
            enum=None,
            status="known",
            provenance=(
                P_d4919fe040ff8f0c55d9,
                P_395d6835593785ebb5f0,
            ),
            xml_aliases=(),
        ),
        "dtd.constraint.ignore_unconnected_atoms": PropertyMetadata(
            owners=("constraint",),
            name="ignore_unconnected_atoms",
            xml_name="IgnoreUnconnectedAtoms",
            storage="attribute",
            cdx_id=2950,
            cdx_constant="kCDXProp_IgnoreUnconnectedAtoms",
            datatype="boolean",
            codec="bool",
            required=False,
            default=False,
            cardinality="one",
            reference_target=None,
            reference_many=False,
            enum=None,
            status="known",
            provenance=(
                P_7e187206c5054c7a31c8,
                P_15b5b13e1f24595e8e6b,
            ),
            xml_aliases=(),
        ),
        "dtd.constraint.point_is_directed": PropertyMetadata(
            owners=("constraint",),
            name="point_is_directed",
            xml_name="PointIsDirected",
            storage="attribute",
            cdx_id=None,
            cdx_constant=None,
            datatype="boolean",
            codec="bool",
            required=False,
            default=False,
            cardinality="one",
            reference_target=None,
            reference_many=False,
            enum=None,
            status="known",
            provenance=(P_68fecebb0c4ad436cb89,),
            xml_aliases=(),
        ),
    }
)
