# AUTO-GENERATED. DO NOT EDIT DIRECTLY.
"""Properties grouped by logical schema owner: fragment."""

from __future__ import annotations

from collections.abc import Mapping
from types import MappingProxyType
from typing import Final

from ..provenance.revvity_dtd import (
    P_4a78f20529b8c15e55dd,
    P_5bca45f29d16c0fb737c,
    P_21fc3d96af4cc5ed2849,
    P_a667421f6a8bddf9d12f,
    P_ab978974864179e0db65,
    P_b32ceeb689fcf448323c,
    P_d170ec64577ebe66c18e,
)
from ..provenance.sdk_page_fragment import (
    P_024b4b96e6ffa1706101,
    P_4b12f2e2063e24bf5e9b,
    P_51a76461175ad7b03c4f,
    P_ca0dafd0db14ab014690,
    P_ccf08c339984076122f8,
    P_e0e9bb1ffe2d62f1ba65,
)
from ..types import PropertyMetadata

PROPERTY_METADATA_GROUP: Final[Mapping[str, PropertyMetadata]] = MappingProxyType(
    {
        "dtd.fragment.absolute": PropertyMetadata(
            owners=("fragment",),
            name="absolute",
            xml_name="Absolute",
            storage="attribute",
            cdx_id=1281,
            cdx_constant="kCDXProp_Mole_Absolute",
            datatype="boolean",
            codec="bool",
            required=False,
            default=False,
            cardinality="one",
            reference_target=None,
            reference_many=False,
            enum=None,
            status="known",
            provenance=(
                P_a667421f6a8bddf9d12f,
                P_e0e9bb1ffe2d62f1ba65,
            ),
            xml_aliases=(),
        ),
        "dtd.fragment.connection_order": PropertyMetadata(
            owners=("fragment",),
            name="connection_order",
            xml_name="ConnectionOrder",
            storage="attribute",
            cdx_id=1285,
            cdx_constant="kCDXProp_Frag_ConnectionOrder",
            datatype="object_id",
            codec="object_id_list",
            required=False,
            default=None,
            cardinality="many",
            reference_target="*",
            reference_many=True,
            enum=None,
            status="known",
            provenance=(
                P_21fc3d96af4cc5ed2849,
                P_4b12f2e2063e24bf5e9b,
            ),
            xml_aliases=(),
        ),
        "dtd.fragment.formula": PropertyMetadata(
            owners=("fragment",),
            name="formula",
            xml_name="Formula",
            storage="attribute",
            cdx_id=1283,
            cdx_constant="kCDXProp_Mole_Formula",
            datatype="string",
            codec="string",
            required=False,
            default=None,
            cardinality="one",
            reference_target=None,
            reference_many=False,
            enum=None,
            status="known",
            provenance=(
                P_ab978974864179e0db65,
                P_ca0dafd0db14ab014690,
            ),
            xml_aliases=(),
        ),
        "dtd.fragment.racemic": PropertyMetadata(
            owners=("fragment",),
            name="racemic",
            xml_name="Racemic",
            storage="attribute",
            cdx_id=1280,
            cdx_constant="kCDXProp_Mole_Racemic",
            datatype="boolean",
            codec="bool",
            required=False,
            default=False,
            cardinality="one",
            reference_target=None,
            reference_many=False,
            enum=None,
            status="known",
            provenance=(
                P_4a78f20529b8c15e55dd,
                P_51a76461175ad7b03c4f,
            ),
            xml_aliases=(),
        ),
        "dtd.fragment.relative": PropertyMetadata(
            owners=("fragment",),
            name="relative",
            xml_name="Relative",
            storage="attribute",
            cdx_id=1282,
            cdx_constant="kCDXProp_Mole_Relative",
            datatype="boolean",
            codec="bool",
            required=False,
            default=False,
            cardinality="one",
            reference_target=None,
            reference_many=False,
            enum=None,
            status="known",
            provenance=(
                P_d170ec64577ebe66c18e,
                P_024b4b96e6ffa1706101,
            ),
            xml_aliases=(),
        ),
        "dtd.fragment.sequence_type": PropertyMetadata(
            owners=("fragment",),
            name="sequence_type",
            xml_name="SequenceType",
            storage="attribute",
            cdx_id=None,
            cdx_constant=None,
            datatype="string",
            codec="string",
            required=False,
            default="Unknown",
            cardinality="one",
            reference_target=None,
            reference_many=False,
            enum="dtd.sequence_type.35f3b725",
            status="known",
            provenance=(P_b32ceeb689fcf448323c,),
            xml_aliases=(),
        ),
        "dtd.fragment.weight": PropertyMetadata(
            owners=("fragment",),
            name="weight",
            xml_name="Weight",
            storage="attribute",
            cdx_id=1284,
            cdx_constant="kCDXProp_Mole_Weight",
            datatype="float",
            codec="float",
            required=False,
            default=None,
            cardinality="one",
            reference_target=None,
            reference_many=False,
            enum=None,
            status="known",
            provenance=(
                P_5bca45f29d16c0fb737c,
                P_ccf08c339984076122f8,
            ),
            xml_aliases=(),
        ),
    }
)
