# AUTO-GENERATED. DO NOT EDIT DIRECTLY.
"""Properties grouped by logical schema owner: gep_plate."""

from __future__ import annotations

from collections.abc import Mapping
from types import MappingProxyType
from typing import Final

from ..provenance.revvity_dtd import (
    P_0d06d1d3027d785dd72f,
    P_1e4c6bd47704c586fb76,
    P_5cb24370f0a8610339ee,
    P_37fa4070b4af84b93382,
    P_abaabb7c3bcad37caadd,
    P_f9226407ab4abbaeda5a,
)
from ..types import PropertyMetadata

PROPERTY_METADATA_GROUP: Final[Mapping[str, PropertyMetadata]] = MappingProxyType(
    {
        "dtd.gepplate.axis_width": PropertyMetadata(
            owners=("gep_plate",),
            name="axis_width",
            xml_name="AxisWidth",
            storage="attribute",
            cdx_id=None,
            cdx_constant=None,
            datatype="string",
            codec="string",
            required=False,
            default=None,
            cardinality="one",
            reference_target=None,
            reference_many=False,
            enum=None,
            status="known",
            provenance=(P_f9226407ab4abbaeda5a,),
            xml_aliases=(),
        ),
        "dtd.gepplate.end_range": PropertyMetadata(
            owners=("gep_plate",),
            name="end_range",
            xml_name="EndRange",
            storage="attribute",
            cdx_id=None,
            cdx_constant=None,
            datatype="string",
            codec="string",
            required=False,
            default=None,
            cardinality="one",
            reference_target=None,
            reference_many=False,
            enum=None,
            status="known",
            provenance=(P_0d06d1d3027d785dd72f,),
            xml_aliases=(),
        ),
        "dtd.gepplate.labels_angle": PropertyMetadata(
            owners=("gep_plate",),
            name="labels_angle",
            xml_name="LabelsAngle",
            storage="attribute",
            cdx_id=None,
            cdx_constant=None,
            datatype="string",
            codec="string",
            required=False,
            default=None,
            cardinality="one",
            reference_target=None,
            reference_many=False,
            enum=None,
            status="known",
            provenance=(P_5cb24370f0a8610339ee,),
            xml_aliases=(),
        ),
        "dtd.gepplate.show_scale": PropertyMetadata(
            owners=("gep_plate",),
            name="show_scale",
            xml_name="ShowScale",
            storage="attribute",
            cdx_id=None,
            cdx_constant=None,
            datatype="boolean",
            codec="bool",
            required=False,
            default=False,
            cardinality="one",
            reference_target=None,
            reference_many=False,
            enum=None,
            status="known",
            provenance=(P_37fa4070b4af84b93382,),
            xml_aliases=(),
        ),
        "dtd.gepplate.start_range": PropertyMetadata(
            owners=("gep_plate",),
            name="start_range",
            xml_name="StartRange",
            storage="attribute",
            cdx_id=None,
            cdx_constant=None,
            datatype="string",
            codec="string",
            required=False,
            default=None,
            cardinality="one",
            reference_target=None,
            reference_many=False,
            enum=None,
            status="known",
            provenance=(P_1e4c6bd47704c586fb76,),
            xml_aliases=(),
        ),
        "dtd.gepplate.unit_id": PropertyMetadata(
            owners=("gep_plate",),
            name="unit_id",
            xml_name="UnitID",
            storage="attribute",
            cdx_id=None,
            cdx_constant=None,
            datatype="string",
            codec="string",
            required=False,
            default=None,
            cardinality="one",
            reference_target=None,
            reference_many=False,
            enum=None,
            status="known",
            provenance=(P_abaabb7c3bcad37caadd,),
            xml_aliases=(),
        ),
    }
)
