# AUTO-GENERATED. DO NOT EDIT DIRECTLY.
"""Properties grouped by logical schema owner: reaction_step."""

from __future__ import annotations

from collections.abc import Mapping
from types import MappingProxyType
from typing import Final

from ..provenance.revvity_dtd import (
    P_06a893220d946f301062,
    P_07f9d17dfa623f0833d0,
    P_5fcf351d3ec8c9afcc9c,
    P_bc8b4652bec516f035ca,
    P_bf76bee86ded105b5e97,
    P_c87cc52b95d66126ca5f,
    P_e9540d9695fb73414dad,
    P_eef18b0c4bdfc60edfdf,
    P_f03e35f47e1327794933,
)
from ..provenance.sdk_page_step import (
    P_0d44e5e6f54bc328f93f,
    P_017dd0105e30727f1029,
    P_4f97057078107ac11ab4,
    P_94ea208a1554499fc9ff,
    P_720ca4271639a8b6be86,
    P_a3624f5e84c96aa2170c,
    P_c3c67771239f0d0d6099,
    P_e3ddd204d837bd441252,
    P_e76136dbcc7e5e09f630,
)
from ..provenance.sdk_step import (
    P_9c52a26a3970e8437a40,
    P_30bae66a7e73653dc67a,
    P_efebae1ec31022e05453,
)
from ..types import PropertyMetadata

PROPERTY_METADATA_GROUP: Final[Mapping[str, PropertyMetadata]] = MappingProxyType(
    {
        "dtd.step.reaction_step_atom_map": PropertyMetadata(
            owners=("reaction_step",),
            name="reaction_step_atom_map",
            xml_name="ReactionStepAtomMap",
            storage="attribute",
            cdx_id=3072,
            cdx_constant="kCDXProp_ReactionStep_Atom_Map",
            datatype="object_id",
            codec="object_id_list",
            required=False,
            default=None,
            cardinality="many",
            reference_target="*",
            reference_many=True,
            enum=None,
            status="known",
            provenance=(
                P_e9540d9695fb73414dad,
                P_94ea208a1554499fc9ff,
            ),
            xml_aliases=(),
        ),
        "dtd.step.reaction_step_atom_map_auto": PropertyMetadata(
            owners=("reaction_step",),
            name="reaction_step_atom_map_auto",
            xml_name="ReactionStepAtomMapAuto",
            storage="attribute",
            cdx_id=3080,
            cdx_constant="kCDXProp_ReactionStep_Atom_Map_Auto",
            datatype="object_id",
            codec="object_id_list",
            required=False,
            default=None,
            cardinality="many",
            reference_target="*",
            reference_many=True,
            enum=None,
            status="known",
            provenance=(
                P_f03e35f47e1327794933,
                P_720ca4271639a8b6be86,
            ),
            xml_aliases=(),
        ),
        "dtd.step.reaction_step_atom_map_manual": PropertyMetadata(
            owners=("reaction_step",),
            name="reaction_step_atom_map_manual",
            xml_name="ReactionStepAtomMapManual",
            storage="attribute",
            cdx_id=3079,
            cdx_constant="kCDXProp_ReactionStep_Atom_Map_Manual",
            datatype="object_id",
            codec="object_id_list",
            required=False,
            default=None,
            cardinality="many",
            reference_target="*",
            reference_many=True,
            enum=None,
            status="known",
            provenance=(
                P_5fcf351d3ec8c9afcc9c,
                P_e3ddd204d837bd441252,
            ),
            xml_aliases=(),
        ),
        "dtd.step.reaction_step_objects_above_arrow": PropertyMetadata(
            owners=("reaction_step",),
            name="reaction_step_objects_above_arrow",
            xml_name="ReactionStepObjectsAboveArrow",
            storage="attribute",
            cdx_id=3077,
            cdx_constant="kCDXProp_ReactionStep_ObjectsAboveArrow",
            datatype="object_id",
            codec="object_id_list",
            required=False,
            default=None,
            cardinality="many",
            reference_target="*",
            reference_many=True,
            enum=None,
            status="known",
            provenance=(
                P_07f9d17dfa623f0833d0,
                P_a3624f5e84c96aa2170c,
            ),
            xml_aliases=(),
        ),
        "dtd.step.reaction_step_objects_below_arrow": PropertyMetadata(
            owners=("reaction_step",),
            name="reaction_step_objects_below_arrow",
            xml_name="ReactionStepObjectsBelowArrow",
            storage="attribute",
            cdx_id=3078,
            cdx_constant="kCDXProp_ReactionStep_ObjectsBelowArrow",
            datatype="object_id",
            codec="object_id_list",
            required=False,
            default=None,
            cardinality="many",
            reference_target="*",
            reference_many=True,
            enum=None,
            status="known",
            provenance=(
                P_bc8b4652bec516f035ca,
                P_e76136dbcc7e5e09f630,
            ),
            xml_aliases=(),
        ),
        "dtd.step.reaction_step_plusses": PropertyMetadata(
            owners=("reaction_step",),
            name="reaction_step_plusses",
            xml_name="ReactionStepPlusses",
            storage="attribute",
            cdx_id=3075,
            cdx_constant="kCDXProp_ReactionStep_Plusses",
            datatype="object_id",
            codec="object_id_list",
            required=False,
            default=None,
            cardinality="many",
            reference_target="*",
            reference_many=True,
            enum=None,
            status="known",
            provenance=(
                P_bf76bee86ded105b5e97,
                P_0d44e5e6f54bc328f93f,
            ),
            xml_aliases=(),
        ),
        "reaction_step.arrows": PropertyMetadata(
            owners=("reaction_step",),
            name="arrows",
            xml_name="ReactionStepArrows",
            storage="attribute",
            cdx_id=3076,
            cdx_constant="kCDXProp_ReactionStep_Arrows",
            datatype="object_id",
            codec="object_id_list",
            required=False,
            default=None,
            cardinality="many",
            reference_target="*",
            reference_many=True,
            enum=None,
            status="known",
            provenance=(
                P_30bae66a7e73653dc67a,
                P_06a893220d946f301062,
                P_c3c67771239f0d0d6099,
            ),
            xml_aliases=(),
        ),
        "reaction_step.products": PropertyMetadata(
            owners=("reaction_step",),
            name="products",
            xml_name="ReactionStepProducts",
            storage="attribute",
            cdx_id=3074,
            cdx_constant="kCDXProp_ReactionStep_Products",
            datatype="object_id",
            codec="object_id_list",
            required=False,
            default=None,
            cardinality="many",
            reference_target="*",
            reference_many=True,
            enum=None,
            status="known",
            provenance=(
                P_efebae1ec31022e05453,
                P_eef18b0c4bdfc60edfdf,
                P_4f97057078107ac11ab4,
            ),
            xml_aliases=(),
        ),
        "reaction_step.reactants": PropertyMetadata(
            owners=("reaction_step",),
            name="reactants",
            xml_name="ReactionStepReactants",
            storage="attribute",
            cdx_id=3073,
            cdx_constant="kCDXProp_ReactionStep_Reactants",
            datatype="object_id",
            codec="object_id_list",
            required=False,
            default=None,
            cardinality="many",
            reference_target="*",
            reference_many=True,
            enum=None,
            status="known",
            provenance=(
                P_9c52a26a3970e8437a40,
                P_c87cc52b95d66126ca5f,
                P_017dd0105e30727f1029,
            ),
            xml_aliases=(),
        ),
    }
)
