# AUTO-GENERATED. DO NOT EDIT DIRECTLY.
"""Properties grouped by logical schema owner: sg_datum."""

from __future__ import annotations

from collections.abc import Mapping
from types import MappingProxyType
from typing import Final

from ..provenance.revvity_dtd import (
    P_3b15cc8d2f3c41a885ca,
    P_5f54cd60923c3a419ee1,
    P_9f39c6caf839ddc58e7b,
    P_85e9068931f95b4fad73,
    P_230d2d13103e9a948685,
    P_313d0e7ab49dd8037de3,
)
from ..types import PropertyMetadata

PROPERTY_METADATA_GROUP: Final[Mapping[str, PropertyMetadata]] = MappingProxyType(
    {
        "dtd.sgdatum.is_edited": PropertyMetadata(
            owners=("sg_datum",),
            name="is_edited",
            xml_name="IsEdited",
            storage="attribute",
            cdx_id=None,
            cdx_constant=None,
            datatype="boolean",
            codec="bool",
            required=False,
            default=False,
            cardinality="one",
            reference_target=None,
            reference_many=False,
            enum=None,
            status="known",
            provenance=(P_230d2d13103e9a948685,),
            xml_aliases=(),
        ),
        "dtd.sgdatum.is_hidden": PropertyMetadata(
            owners=("sg_datum",),
            name="is_hidden",
            xml_name="IsHidden",
            storage="attribute",
            cdx_id=None,
            cdx_constant=None,
            datatype="boolean",
            codec="bool",
            required=False,
            default=False,
            cardinality="one",
            reference_target=None,
            reference_many=False,
            enum=None,
            status="known",
            provenance=(P_9f39c6caf839ddc58e7b,),
            xml_aliases=(),
        ),
        "dtd.sgdatum.is_read_only": PropertyMetadata(
            owners=("sg_datum",),
            name="is_read_only",
            xml_name="IsReadOnly",
            storage="attribute",
            cdx_id=None,
            cdx_constant=None,
            datatype="boolean",
            codec="bool",
            required=False,
            default=False,
            cardinality="one",
            reference_target=None,
            reference_many=False,
            enum=None,
            status="known",
            provenance=(P_85e9068931f95b4fad73,),
            xml_aliases=(),
        ),
        "dtd.sgdatum.sg_data_type": PropertyMetadata(
            owners=("sg_datum",),
            name="sg_data_type",
            xml_name="SGDataType",
            storage="attribute",
            cdx_id=None,
            cdx_constant=None,
            datatype="string",
            codec="string",
            required=False,
            default=None,
            cardinality="one",
            reference_target=None,
            reference_many=False,
            enum=None,
            status="known",
            provenance=(P_5f54cd60923c3a419ee1,),
            xml_aliases=(),
        ),
        "dtd.sgdatum.sg_data_value": PropertyMetadata(
            owners=("sg_datum",),
            name="sg_data_value",
            xml_name="SGDataValue",
            storage="attribute",
            cdx_id=None,
            cdx_constant=None,
            datatype="string",
            codec="string",
            required=False,
            default=None,
            cardinality="one",
            reference_target=None,
            reference_many=False,
            enum=None,
            status="known",
            provenance=(P_313d0e7ab49dd8037de3,),
            xml_aliases=(),
        ),
        "dtd.sgdatum.sg_property_type": PropertyMetadata(
            owners=("sg_datum",),
            name="sg_property_type",
            xml_name="SGPropertyType",
            storage="attribute",
            cdx_id=None,
            cdx_constant=None,
            datatype="string",
            codec="string",
            required=False,
            default=None,
            cardinality="one",
            reference_target=None,
            reference_many=False,
            enum=None,
            status="known",
            provenance=(P_3b15cc8d2f3c41a885ca,),
            xml_aliases=(),
        ),
    }
)
