# AUTO-GENERATED. DO NOT EDIT DIRECTLY.
"""Metadata for the BioShapeType enum spec."""

from __future__ import annotations

from ..provenance.revvity_dtd import P_cf77ea94572077efa9be
from ..types import EnumMetadata, EnumValueMetadata

ENUM_METADATA_ENTRY = EnumMetadata(
    python_name="BioShapeType",
    underlying_datatype="string",
    representation="str",
    values=(
        EnumValueMetadata(
            name="UNDEFINED",
            xml_value="Undefined",
            cdx_value=None,
        ),
        EnumValueMetadata(
            name="VALUE_1_SUBSTRATE_ENZYME",
            xml_value="1SubstrateEnzyme",
            cdx_value=None,
        ),
        EnumValueMetadata(
            name="VALUE_2_SUBSTRATE_ENZYME",
            xml_value="2SubstrateEnzyme",
            cdx_value=None,
        ),
        EnumValueMetadata(
            name="RECEPTOR",
            xml_value="Receptor",
            cdx_value=None,
        ),
        EnumValueMetadata(
            name="G_PROTEIN_ALPHA",
            xml_value="GProteinAlpha",
            cdx_value=None,
        ),
        EnumValueMetadata(
            name="G_PROTEIN_BETA",
            xml_value="GProteinBeta",
            cdx_value=None,
        ),
        EnumValueMetadata(
            name="G_PROTEIN_GAMMA",
            xml_value="GProteinGamma",
            cdx_value=None,
        ),
        EnumValueMetadata(
            name="IMMUNOGLOBIN",
            xml_value="Immunoglobin",
            cdx_value=None,
        ),
        EnumValueMetadata(
            name="ION_CHANNEL",
            xml_value="IonChannel",
            cdx_value=None,
        ),
        EnumValueMetadata(
            name="ENDOPLASMIC_RETICULUM",
            xml_value="EndoplasmicReticulum",
            cdx_value=None,
        ),
        EnumValueMetadata(
            name="GOLGI",
            xml_value="Golgi",
            cdx_value=None,
        ),
        EnumValueMetadata(
            name="MEMBRANE_LINE",
            xml_value="MembraneLine",
            cdx_value=None,
        ),
        EnumValueMetadata(
            name="MEMBRANE_ARC",
            xml_value="MembraneArc",
            cdx_value=None,
        ),
        EnumValueMetadata(
            name="MEMBRANE_ELLIPSE",
            xml_value="MembraneEllipse",
            cdx_value=None,
        ),
        EnumValueMetadata(
            name="MEMBRANE_MICELLE",
            xml_value="MembraneMicelle",
            cdx_value=None,
        ),
        EnumValueMetadata(
            name="DNA",
            xml_value="DNA",
            cdx_value=None,
        ),
        EnumValueMetadata(
            name="HELIX_PROTEIN",
            xml_value="HelixProtein",
            cdx_value=None,
        ),
        EnumValueMetadata(
            name="MITOCHONDRION",
            xml_value="Mitochondrion",
            cdx_value=None,
        ),
        EnumValueMetadata(
            name="CLOUD",
            xml_value="Cloud",
            cdx_value=None,
        ),
        EnumValueMetadata(
            name="T_RNA",
            xml_value="tRNA",
            cdx_value=None,
        ),
        EnumValueMetadata(
            name="RIBOSOME_A",
            xml_value="RibosomeA",
            cdx_value=None,
        ),
        EnumValueMetadata(
            name="RIBOSOME_B",
            xml_value="RibosomeB",
            cdx_value=None,
        ),
    ),
    status="known",
    provenance=(P_cf77ea94572077efa9be,),
)
