# AUTO-GENERATED. DO NOT EDIT DIRECTLY.
"""Metadata for the OrbitalType enum spec."""

from __future__ import annotations

from ..provenance.revvity_dtd import P_d50743694af8af082ce6
from ..provenance.sdk_page_graphic import P_5aec61b79dc5746e0973
from ..types import EnumMetadata, EnumValueMetadata

ENUM_METADATA_ENTRY = EnumMetadata(
    python_name="OrbitalType",
    underlying_datatype="string",
    representation="str",
    values=(
        EnumValueMetadata(
            name="S",
            xml_value="s",
            cdx_value=None,
        ),
        EnumValueMetadata(
            name="P",
            xml_value="p",
            cdx_value=None,
        ),
        EnumValueMetadata(
            name="OVAL",
            xml_value="oval",
            cdx_value=None,
        ),
        EnumValueMetadata(
            name="LOBE",
            xml_value="lobe",
            cdx_value=None,
        ),
        EnumValueMetadata(
            name="HYBRID_PLUS",
            xml_value="hybridPlus",
            cdx_value=None,
        ),
        EnumValueMetadata(
            name="HYBRID_MINUS",
            xml_value="hybridMinus",
            cdx_value=None,
        ),
        EnumValueMetadata(
            name="DZ2_PLUS",
            xml_value="dz2Plus",
            cdx_value=None,
        ),
        EnumValueMetadata(
            name="DZ2_MINUS",
            xml_value="dz2Minus",
            cdx_value=None,
        ),
        EnumValueMetadata(
            name="DXY",
            xml_value="dxy",
            cdx_value=None,
        ),
        EnumValueMetadata(
            name="S_SHADED",
            xml_value="sShaded",
            cdx_value=None,
        ),
        EnumValueMetadata(
            name="S_FILLED",
            xml_value="sFilled",
            cdx_value=None,
        ),
        EnumValueMetadata(
            name="OVAL_SHADED",
            xml_value="ovalShaded",
            cdx_value=None,
        ),
        EnumValueMetadata(
            name="OVAL_FILLED",
            xml_value="ovalFilled",
            cdx_value=None,
        ),
        EnumValueMetadata(
            name="LOBE_SHADED",
            xml_value="lobeShaded",
            cdx_value=None,
        ),
        EnumValueMetadata(
            name="P_SHADED",
            xml_value="pShaded",
            cdx_value=None,
        ),
        EnumValueMetadata(
            name="LOBE_FILLED",
            xml_value="lobeFilled",
            cdx_value=None,
        ),
        EnumValueMetadata(
            name="P_FILLED",
            xml_value="pFilled",
            cdx_value=None,
        ),
        EnumValueMetadata(
            name="HYBRID_PLUS_FILLED",
            xml_value="hybridPlusFilled",
            cdx_value=None,
        ),
        EnumValueMetadata(
            name="HYBRID_MINUS_FILLED",
            xml_value="hybridMinusFilled",
            cdx_value=None,
        ),
        EnumValueMetadata(
            name="DZ2_PLUS_FILLED",
            xml_value="dz2PlusFilled",
            cdx_value=None,
        ),
        EnumValueMetadata(
            name="DZ2_MINUS_FILLED",
            xml_value="dz2MinusFilled",
            cdx_value=None,
        ),
        EnumValueMetadata(
            name="DXY_FILLED",
            xml_value="dxyFilled",
            cdx_value=None,
        ),
    ),
    status="known",
    provenance=(
        P_d50743694af8af082ce6,
        P_5aec61b79dc5746e0973,
    ),
)
